### ISSUE TITLE
Update Jest to v26 and address test failures

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2766]
The automatic dependency update for Jest currently fails (#2689) because there are a bunch of test failures with that new version.

This could mean that the tests are broken, or that the tested code is actually broken, both of which would be bad.

**Failure 1: Save/Preview/Publish buttons**

Tests: [`assets/src/edit-story/components/header/test/buttons.js`](https://github.com/google/web-stories-wp/blob/e1899ea7ae117fd4da62da7e138dc3988a08215f/assets/src/edit-story/components/header/test/buttons.js)

Log:

```
  ● buttons › should open draft preview when clicking on Preview via about:blank

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: called with 0 arguments

    Number of calls: 0

      186 |     fireEvent.click(previewButton);
      187 | 
    > 188 |     expect(saveStory).toHaveBeenCalledWith();
          |                       ^
      189 |     expect(mockedOpen).toHaveBeenCalledWith('about:blank', 'story-preview');
      190 |     expect(popup.location.replace).toHaveBeenCalledWith(
      191 |       'https://example.com/?preview=true'

      at Object.<anonymous> (assets/src/edit-story/components/header/test/buttons.js:188:23)

  ● buttons › should open draft preview when clicking on Preview via about:blank

    TypeError: Right-hand side of 'instanceof' is not an object

      at getActiveElementDeep (node_modules/react-dom/cjs/react-dom.development.js:6941:18)
      at getSelectionInformation (node_modules/react-dom/cjs/react-dom.development.js:6972:21)
      at prepareForCommit (node_modules/react-dom/cjs/react-dom.development.js:7463:26)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22474:5)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24774:5)
      at node_modules/react-dom/cjs/react-dom.development.js:24884:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at Object.unmountComponentAtNode (node_modules/react-dom/cjs/react-dom.development.js:24883:5)
      at cleanupAtContainer (node_modules/@testing-library/react/dist/pure.js:141:21)
          at Set.forEach (<anonymous>)
      at cleanup (node_modules/@testing-library/react/dist/pure.js:132:21)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:30:31)

  ● buttons › should open preview for a published story when clicking on Preview via about:blank

    TypeError: Right-hand side of 'instanceof' is not an object

      36 | 
      37 | const renderWithTheme = (ui, options) =>
    > 38 |   render(ui, {
         |   ^
      39 |     wrapper: WithThemeProvider,
      40 |     queries: {
      41 |       ...queries,

      at getActiveElementDeep (node_modules/react-dom/cjs/react-dom.development.js:6941:18)
      at getSelectionInformation (node_modules/react-dom/cjs/react-dom.development.js:6972:21)
      at prepareForCommit (node_modules/react-dom/cjs/react-dom.development.js:7463:26)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22474:5)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at node_modules/react-dom/cjs/react-dom.development.js:24758:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24757:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24840:10)
      at node_modules/@testing-library/react/dist/pure.js:100:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at render (node_modules/@testing-library/react/dist/pure.js:96:26)
      at renderWithTheme (assets/src/edit-story/testUtils/renderWithTheme.js:38:3)
      at setupButtons (assets/src/edit-story/components/header/test/buttons.js:59:25)
      at Object.<anonymous> (assets/src/edit-story/components/header/test/buttons.js:198:37)

  ● buttons › should open preview for a published story when clicking on Preview via about:blank

    TypeError: Right-hand side of 'instanceof' is not an object

      at getActiveElementDeep (node_modules/react-dom/cjs/react-dom.development.js:6941:18)
      at getSelectionInformation (node_modules/react-dom/cjs/react-dom.development.js:6972:21)
      at prepareForCommit (node_modules/react-dom/cjs/react-dom.development.js:7463:26)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22474:5)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24774:5)
      at node_modules/react-dom/cjs/react-dom.development.js:24884:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at Object.unmountComponentAtNode (node_modules/react-dom/cjs/react-dom.development.js:24883:5)
      at cleanupAtContainer (node_modules/@testing-library/react/dist/pure.js:141:21)
          at Set.forEach (<anonymous>)
      at cleanup (node_modules/@testing-library/react/dist/pure.js:132:21)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:30:31)
```

**Failure 2: Copy Paste Handler**

Tests: [`assets/src/edit-story/utils/test/nativeCopyPasteExpected.js`](https://github.com/google/web-stories-wp/blob/e1899ea7ae117fd4da62da7e138dc3988a08215f/assets/src/edit-story/utils/test/nativeCopyPasteExpected.js)

Log:

```
  ● nativeCopyPasteExpected › should detect selection correctly for different inputs

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      50 |     document.body.appendChild(incorrectInput);
      51 |     incorrectInput.focus();
    > 52 |     expect(nativeCopyPasteExpected()).toBe(false);
         |                                       ^
      53 | 
      54 |     windowSpy.mockRestore();
      55 |   });

      at Object.<anonymous> (assets/src/edit-story/utils/test/nativeCopyPasteExpected.js:52:39)

  ● useGlobalClipboardHandlers › should call the set handlers as expected

    TypeError: Illegal invocation

      at Object.addEventListener (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:71:15)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10016:14)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10073:31)
      at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12971:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1775:10)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12873:3)
      at finishSyncRender (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12384:3)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12370:7)
```

**Comment by swissspidy** [comment]
https://jestjs.io/blog/2020/05/05/jest-26#new-fake-timers
