### ISSUE TITLE
Improve reliability of failing Karma tests

### ISSUE THREAD

**Issue by zachhale** [GoogleForCreators/web-stories-wp#6085]
## Feature Description

Karma tests frequently fail seemingly randomly requiring re-runs in CI. This ticket is a place to make notes of which tests are failing to try to find and prioritize improvements.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by zachhale** [comment]
https://github.com/google/web-stories-wp/pull/5945/checks?check_run_id=1787716392

```
PageMenu integration
    add a text
      delete the element, restore, and delete again
        ✗ using page menu
	Error: Not ready: only found 0 media elements
```

```
  CUJ: Creator can Apply a Page Layout
    ✓ should confirm and cancel applying to a page with changes
28 01 2021 22:41:58.653:ERROR [karma-server]: UncaughtException:: Cannot read property 'split' of undefined
28 01 2021 22:41:58.792:ERROR [karma-server]: TypeError: Cannot read property 'split' of undefined
    at /home/runner/work/web-stories-wp/web-stories-wp/karma/karma-cuj-reporter/index.cjs:68:34
    at Array.forEach (<anonymous>)
    at CUJReporter.onSpecComplete (/home/runner/work/web-stories-wp/web-stories-wp/karma/karma-cuj-reporter/index.cjs:62:11)
    at Server.<anonymous> (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/karma/lib/events.js:40:26)
    at Server.emit (events.js:327:22)
    at Browser.onResult (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/karma/lib/browser.js:159:20)
    at Socket.<anonymous> (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/karma/lib/browser.js:209:42)
    at Socket.emit (events.js:315:20)
    at /home/runner/work/web-stories-wp/web-stories-wp/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
 which is followed closely by before failing the karma run with:
```
28 01 2021 22:41:59.750:ERROR [config]: Error in config file!
 Error: ENOENT: no such file or directory, open 'build/karma-edit-story-failed-tests.txt'
    at Object.openSync (fs.js:476:3)
    at readFileSync (fs.js:377:35)
    at module.exports (/home/runner/work/web-stories-wp/web-stories-wp/karma-edit-story.config.cjs:33:20)
    at Object.parseConfig (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/karma/lib/config.js:396:5)
    at new Server (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/karma/lib/server.js:64:24)
    at Object.exports.run (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/karma/lib/cli.js:258:7)
    at Object.<anonymous> (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/karma/bin/karma:3:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'build/karma-edit-story-failed-tests.txt'
}
```

**Comment by zachhale** [comment]
From a subsequent run on the same PR as above: https://github.com/google/web-stories-wp/pull/5945/checks?check_run_id=1787981228

```
  Border Radius Panel
    CUJ: Creator can Manipulate Shape: Border Radius
      ✗ should allow the user to add border radius for text element
	Error: Not ready: only found 0 media elements
```

```
  CUJ: Text Sets (Text and Shape Combinations): Using Text Sets
    ...
    ✗ should allow user to drag and drop text set onto page
	Error: Expected 0 to be greater than 1.
	    at <Jasmine>
	    at UserContext.<anonymous> (webpack:///assets/src/edit-story/components/library/panes/text/karma/textSets.cuj.karma.js:85:56 <- assets/src/edit-story/karma-tests.js:348178:56)
```

**Comment by zachhale** [comment]
Another run of that PR: https://github.com/google/web-stories-wp/pull/5945/checks?check_run_id=1788013200

```
  CUJ: Creator can Add and Write Text: Select an individual word to edit
    CUJ: Creator Can Style Text: Apply B, Apply U, Apply I, Set text color, Set kerning
      ✗ should apply inline formats correctly for both single style and multiple styles
	Error: Not ready: only found 0 media elements
```

```
  Image Editor
    CUJ: Creator Can Manipulate an Image/Video on Canvas: Enter edit mode
      edit mode
        ✗ should mount editor
	TestingLibraryElementError: Unable to find an accessible element with the role "region" and name "Edit layer"
```

**Comment by swissspidy** [comment]
> Another run of that PR: [#5945 (checks)](https://github.com/google/web-stories-wp/pull/5945/checks?check_run_id=1788013200)
> 
> ```
>   CUJ: Creator can Add and Write Text: Select an individual word to edit
>     CUJ: Creator Can Style Text: Apply B, Apply U, Apply I, Set text color, Set kerning
>       ✗ should apply inline formats correctly for both single style and multiple styles
> 	Error: Not ready: only found 0 media elements
> ```
> 
> ```
>   Image Editor
>     CUJ: Creator Can Manipulate an Image/Video on Canvas: Enter edit mode
>       edit mode
>         ✗ should mount editor
> 	TestingLibraryElementError: Unable to find an accessible element with the role "region" and name "Edit layer"
> ```

Seeing that on a recent run on `main` as well, together with 3 other failures in the same scenario:

https://github.com/google/web-stories-wp/runs/1785299813?check_suite_focus=true#step:8:6964

**Comment by swissspidy** [comment]
Another one:

```
1) retains all foreground animations
     Duplicate
     Expected object to have properties
    scaleDirection: 'scaleIn'
Expected object not to have properties
    whooshInDir: 'rightToLeft'
Expected $.type = 'effect-whoosh-in' to equal 'effect-zoom'.
Expected $.duration = 600 to equal 1000.
Error: Expected object to have properties
    scaleDirection: 'scaleIn'
Expected object not to have properties
    whooshInDir: 'rightToLeft'
Expected $.type = 'effect-whoosh-in' to equal 'effect-zoom'.
Expected $.duration = 600 to equal 1000.

in assets/src/edit-story/karma/copyAndPaste.cuj.karma.js:131:7
```

**Comment by swissspidy** [comment]
closing for now since the tests are quite stable again

Individual flakiness can be handled in separate tickets & PRs
