### ISSUE TITLE
E2E Tests: Debug and fix flakey tests for media insertion

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#7107]
## Bug Description

Test has been failing on some prs. [Relevant slack convo](https://xwp.slack.com/archives/CCCAUAH6F/p1617740209110600)
- https://github.com/google/web-stories-wp/pull/6960/checks?check_run_id=2280215332
- https://github.com/google/web-stories-wp/pull/7067/checks?check_run_id=2272843256

## Expected Behaviour

Test should pass consistently if nothing is wrong.

## Screenshots

Output in CI:
```
Run npm run test:e2e

> test:e2e
> JEST_PUPPETEER_CONFIG=jest-puppeteer.config.cjs jest --runInBand --config=packages/e2e-tests/src/jest.config.js

..........................
  ● Inserting Media from Dialog › should insert an image by clicking on it

    TimeoutError: Element [data-testid="imageElement"] not found

      waiting for function failed: timeout 500ms exceeded

  ● Inserting Media from Dialog › should insert an image by clicking on it

    expect(received).toPassAxeTests(expected)

    Expected page to pass Axe accessibility tests.
    Violations found:
    Rule: "landmark-one-main" (Document must have one main landmark)
    Help: https://dequeuniversity.com/rules/axe/4.1/landmark-one-main?application=axe-puppeteer
    Affected Nodes:
      html
        Fix ALL of the following:
          - Document does not have a main landmark.

    Rule: "list" (<ul> and <ol> must only directly contain <li>, <script> or <template> elements)
    Help: https://dequeuniversity.com/rules/axe/4.1/list?application=axe-puppeteer
    Affected Nodes:
      #__attachments-view-52
        Fix ALL of the following:
          - List element has direct children with a role that is not allowed: checkbox.

      200 |   }
      201 |
    > 202 |   await expect(page).toPassAxeTests({
          |                      ^
      203 |     // Temporary disabled rules to enable initial integration.
      204 |     disabledRules: [
      205 |       'aria-allowed-role',

      at runAxeTestsForStoriesEditor (config/bootstrap.js:202:22)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (config/bootstrap.js:242:3)

..

Error: Process completed with exit code 1.
```

## Additional Context

- Plugin Version: 1.5.1
- WordPress Version: 5.7
- Operating System: macOSX BigSur 11.2.2
- Browser: n/a (chromium in tests)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
`Inserting Media from Media Library` is also flakey and not really working at the moment.
