### ISSUE TITLE
TypeError: Cannot read property 'elements' of undefined

### ISSUE THREAD

**Issue by rodolfotresite** [GoogleForCreators/web-stories-wp#7299]
TypeError: Cannot read property 'elements' of undefined
    at he (https://notizias.site/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=181a8e83d4befb80582d6bbd7b2ea540:20:151645)
    at https://notizias.site/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a936d9cea1bc75252d2.js:2:21896
    at t.a (https://notizias.site/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=181a8e83d4befb80582d6bbd7b2ea540:52:70245)
    at https://notizias.site/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a936d9cea1bc75252d2.js:2:21896
    at gr (https://notizias.site/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=181a8e83d4befb80582d6bbd7b2ea540:20:49080)
    at https://notizias.site/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a936d9cea1bc75252d2.js:2:21896
    at u (https://notizias.site/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=181a8e83d4befb80582d6bbd7b2ea540:32:50320)
    at https://notizias.site/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a936d9cea1bc75252d2.js:2:21896
    at h (https://notizias.site/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=181a8e83d4befb80582d6bbd7b2ea540:32:72554)
    at https://notizias.site/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a936d9cea1bc75252d2.js:2:21896
    at l (https://notizias.site/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=181a8e83d4befb80582d6bbd7b2ea540:52:59001)
    at https://notizias.site/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a936d9cea1bc75252d2.js:2:21896
    at g (https://notizias.site/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=181a8e83d4befb80582d6bbd7b2ea540:20:573798)
    at https://notizias.site/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a936d9cea1bc75252d2.js:2:21896
    at i (https://notizias.site/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=181a8e83d4befb80582d6bbd7b2ea540:20:162943)
    at C (https://notizias.site/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=181a8e83d4befb80582d6bbd7b2ea540:52:79696)
    at Mt (https://notizias.site/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a936d9cea1bc75252d2.js:1:12396)
    at ut (https://notizias.site/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a936d9cea1bc75252d2.js:1:9516)
    at t.a (https://notizias.site/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=181a8e83d4befb80582d6bbd7b2ea540:395:24)
    at s (https://notizias.site/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a936d9cea1bc75252d2.js:1:27533)

**Comment by LuckynaSan** [comment]
@rodolfotresite Thank you for reporting this issue. Do you recall what prompted this error? What did you do when before the error appeared? Did you create a new story, or perhaps use a template?

Could you please open your browser developer tools and check for any [browser console errors](https://imgur.com/KyLAzgH.png)?

What browser and which version are you currently using, and on which operating system (Windows/Mac)? 

Does this still happen with all other plugins disabled and when using another theme like e.g. Twenty Twenty-One?

**Comment by LuckynaSan** [comment]
@rodolfotresite We are going to close your report as we haven’t received a response. Please feel free to open a <a href="https://wordpress.org/support/plugin/web-stories/#new-post">new support topic</a> in the WordPress Web Stories Support Forum if you continue to experience any issues. Thank you!
