### ISSUE TITLE
TypeError: Cannot read property 'elements' of undefined

### ISSUE THREAD

**Issue by iamkoushik21** [GoogleForCreators/web-stories-wp#7828]
TypeError: Cannot read property 'elements' of undefined
    at StoryProvider (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=ff37cf4de0c27948ee722eee22ea56a5:28:81343)
    at https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a3fdd511f14096c9fa6.js:1:121222
    at MetaBoxesProvider (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=ff37cf4de0c27948ee722eee22ea56a5:79:18292)
    at https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a3fdd511f14096c9fa6.js:1:121222
    at SnackbarProvider (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=ff37cf4de0c27948ee722eee22ea56a5:28:20758)
    at https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a3fdd511f14096c9fa6.js:1:121222
    at HistoryProvider (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=ff37cf4de0c27948ee722eee22ea56a5:33:722624)
    at https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a3fdd511f14096c9fa6.js:1:121222
    at Media3pApiProvider (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=ff37cf4de0c27948ee722eee22ea56a5:57:20549)
    at https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a3fdd511f14096c9fa6.js:1:121222
    at FileProvider (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=ff37cf4de0c27948ee722eee22ea56a5:79:2472)
    at https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a3fdd511f14096c9fa6.js:1:121222
    at APIProvider (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=ff37cf4de0c27948ee722eee22ea56a5:28:141209)
    at https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a3fdd511f14096c9fa6.js:1:121222
    at ConfigProvider (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=ff37cf4de0c27948ee722eee22ea56a5:28:131446)
    at g (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=ff37cf4de0c27948ee722eee22ea56a5:79:24486)
    at Ge (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a3fdd511f14096c9fa6.js:1:12396)
    at ue (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a3fdd511f14096c9fa6.js:1:9516)
    at App (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/edit-story.js?ver=ff37cf4de0c27948ee722eee22ea56a5:545:28)
    at FlagsProvider (https://thenewskolkata.in/wp-content/plugins/web-stories/assets/js/vendors-edit-story-stories-dashboard-6a3fdd511f14096c9fa6.js:1:29297)

**Comment by swissspidy** [comment]
Thanks a lot for reporting!

Curious, is this happening for all stories or just specific ones? Does it still happen with all other plugins disabled?

**Comment by iamkoushik21** [comment]
its happening for all stories... not work show error and show submit a
report

**Comment by iamkoushik21** [comment]
this is the problem

**Comment by swissspidy** [comment]
Does it still happen with all other plugins disabled?

**Comment by iamkoushik21** [comment]
Yes,

**Comment by LuckynaSan** [comment]
@iamkoushik21 Hi there! Are you still experiencing this issue with version 1.8.1 of the Web Stories plugin? If so, it would be great to get some more information from you. What did you do when this error appeared? Did you just create a new story? Or perhaps use a template?

Please share your Site Health info with us. You can copy the data from Tools -> Site Health -> Info -> "Copy site info to clipboard"
