### ISSUE TITLE
ColorControls ref warnings in tests

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7876]
## Task Description

Getting the following warnings when running JS unit tests:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ColorControls`.
    at mockConstructor (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/jest-mock/build/index.js:171:19)
    at div
    at row__Row (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/styled-components/src/models/Keyframes.js:20:51)
    at ColorControls (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/design/textStyle/color.js:29:26)
    at div
    at content__Container (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/styled-components/src/models/Keyframes.js:20:51)
    at Content (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/panel/shared/content.js:40:20)
    at /home/runner/work/web-stories-wp/web-stories-wp/node_modules/use-context-selector/src/index.js:29:20
    at section
    at panel__Wrapper (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/styled-components/src/models/Keyframes.js:20:51)
    at Panel (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/panel/panel.js:45:3)
    at SimplePanel (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/panel/simplePanel.js:29:24)
    at textStyle___StyledSimplePanel (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/styled-components/src/models/Keyframes.js:20:51)
    at StylePanel (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/design/textStyle/textStyle.js:34:27)
    at /home/runner/work/web-stories-wp/web-stories-wp/node_modules/use-context-selector/src/index.js:29:20
    at /home/runner/work/web-stories-wp/web-stories-wp/node_modules/use-context-selector/src/index.js:29:20
    at /home/runner/work/web-stories-wp/web-stories-wp/node_modules/use-context-selector/src/index.js:29:20
    at /home/runner/work/web-stories-wp/web-stories-wp/node_modules/use-context-selector/src/index.js:29:20
    at Wrapper (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/design/textStyle/test/textStyle.js:58:20)
    at TestPanel (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/shared/test/_utils.js:34:3)
    at Object.<anonymous>.exports.ThemeProvider (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/styled-components/src/models/ServerStyleSheet.js:66:13)
```

Example run: https://github.com/google/web-stories-wp/pull/7855/checks?check_run_id=2772397125#step:9:37

**Comment by swissspidy** [comment]
IIRC this was fixed at some point
