### ISSUE TITLE
TimeZone / PublishPanel prop type warning

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7877]
## Task Description

Getting the following warnings when running JS unit tests:

```
Warning: Failed prop type: Invalid prop `date` of type `date` supplied to `TimeZone`, expected `string`.
    at TimeZone (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/form/dateTime/timeZone.js:40:21)
    at TimePicker (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/form/dateTime/timePicker.js:131:23)
    at div
    at dateTime__DateTimeWrapper (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/styled-components/src/models/Keyframes.js:20:51)
    at DateTime (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/form/dateTime/dateTime.js:54:3)
    at div
    at popup__Container (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/styled-components/src/models/Keyframes.js:20:51)
    at Popup (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/popup/index.js:63:3)
    at PublishTime (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/document/publish/publishTime.js:42:51)
    at div
    at content__Container (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/styled-components/src/models/Keyframes.js:20:51)
    at Content (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/panel/shared/content.js:40:20)
    at /home/runner/work/web-stories-wp/web-stories-wp/node_modules/use-context-selector/src/index.js:29:20
    at section
    at panel__Wrapper (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/styled-components/src/models/Keyframes.js:20:51)
    at Panel (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/panel/panel.js:45:3)
    at PublishPanel (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/components/panels/document/publish/publish.js:85:7)
    at /home/runner/work/web-stories-wp/web-stories-wp/node_modules/use-context-selector/src/index.js:29:20
    at /home/runner/work/web-stories-wp/web-stories-wp/node_modules/use-context-selector/src/index.js:29:20
    at /home/runner/work/web-stories-wp/web-stories-wp/node_modules/use-context-selector/src/index.js:29:20
    at Object.<anonymous>.exports.ThemeProvider (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/styled-components/src/models/ServerStyleSheet.js:66:13)
    at WithThemeProvider (/home/runner/work/web-stories-wp/web-stories-wp/assets/src/edit-story/testUtils/renderWithTheme.js:33:30)
```

Example run: https://github.com/google/web-stories-wp/pull/7855/checks?check_run_id=2772397125#step:9:61

**Comment by swissspidy** [comment]
This has since been fixed
