### ISSUE TITLE
Flaky: "CUJ: Creator can Add and Write Text.... Adding texts consecutively"

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#8740]
Two flaky tests under `Adding texts consecutively` in textPane.karma.js.

### `should add text presets below each other if added consecutively`

> TypeError: Cannot read properties of undefined (reading 'node')

```
1) should add text presets below each other if added consecutively
     CUJ: Creator can Add and Write Text: Consecutive text presets Adding texts consecutively
     TypeError: Cannot read properties of undefined (reading 'node')

    at webpack:///packages/story-editor/src/components/library/panes/text/karma/textPane.karma.js:82:71 <- packages/story-editor/src/karma-tests.js:710726:134
    at runWithExpensiveErrorDiagnosticsDisabled (webpack:///node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:384:1 <- packages/story-editor/src/karma-tests.js:6493:12)
    at _checkCallback (webpack:///node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1102:1 <- packages/story-editor/src/karma-tests.js:7211:32)
    at _checkRealTimersCallb (webpack:///node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1130:1 <- packages/story-editor/src/karma-tests.js:7239:26)
```
Looks like this line: https://github.com/google/web-stories-wp/blob/c9bfbcd46a1821663cdb5c6310fbbfb691acf119/packages/story-editor/src/components/library/panes/text/karma/textPane.karma.js#L82

Sample run: https://github.com/google/web-stories-wp/runs/3374479670

### `should ensure staggered presets fit on the page`

> TypeError: Cannot read properties of undefined (reading 'node')

```
2) should ensure staggered presets fit on the page
     CUJ: Creator can Add and Write Text: Consecutive text presets Adding texts consecutively
     TypeError: Cannot read properties of undefined (reading 'node')

    at webpack:///packages/story-editor/src/components/library/panes/text/karma/textPane.karma.js:104:69 <- packages/story-editor/src/karma-tests.js:710744:144
    at runWithExpensiveErrorDiagnosticsDisabled (webpack:///node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:384:1 <- packages/story-editor/src/karma-tests.js:6493:12)
    at _checkCallback (webpack:///node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1102:1 <- packages/story-editor/src/karma-tests.js:7211:32)
    at _checkRealTimersCallb (webpack:///node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1130:1 <- packages/story-editor/src/karma-tests.js:7239:26)
```

Looks like this line: https://github.com/google/web-stories-wp/blob/c9bfbcd46a1821663cdb5c6310fbbfb691acf119/packages/story-editor/src/components/library/panes/text/karma/textPane.karma.js#L104

Sample run: https://github.com/google/web-stories-wp/runs/3373444881

**Comment by dreamofabear** [comment]
Seems like both tests are related to clicking "insert text" but not finding the resulting text element. Related to smart text colors feature?

**Comment by miina** [comment]
> Seems like both tests are related to clicking "insert text" but not finding the resulting text element. Related to smart text colors feature?

Yes, this is related to the smart text colors feature, we have it enabled in the tests. It would work as expected without it. Not sure what changed meanwhile though that it started being flaky, that would happen if the insertion would take more time than expected. Or perhaps it was flaky before already?
